#version: '3.8'

#services:
 # nginx:
  #  image: nginx:latest
   # volumes:
    #  - /home/isw147/Desktop/javaproject/nginx/nginx.conf:/etc/nginx/nginx.conf
      
#    ports:
 #     - "80:80"
  #  depends_on:
   #   - demo

#  demo:
 #   build:
  #    context: ./demo
   # ports:
    #  - "8081:8080"


version: '3'
services:
  demo:
    image: demoaug10.2:latest # Replace with your Spring Boot application Docker image
    ports:
      - "8088:8080" # Expose Spring Boot app's port

  nginx:
    image: nginxaug10.1:latest
    ports:
      - "88:80" # Expose Nginx on port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Mount your custom Nginx configuration
      - ./nginx/conf.d:/etc/nginx/conf.d # Mount additional Nginx configurations
      - ./static:/usr/share/nginx/html # Mount your static web files
    depends_on:
      - demo

